// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1GetNotificationV1Response v1 get notification v1 response
//
// swagger:model v1GetNotificationV1Response
type V1GetNotificationV1Response struct {

	// notification
	Notification []*V1UserNotification `json:"notification"`
}

// Validate validates this v1 get notification v1 response
func (m *V1GetNotificationV1Response) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateNotification(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V1GetNotificationV1Response) validateNotification(formats strfmt.Registry) error {
	if swag.IsZero(m.Notification) { // not required
		return nil
	}

	for i := 0; i < len(m.Notification); i++ {
		if swag.IsZero(m.Notification[i]) { // not required
			continue
		}

		if m.Notification[i] != nil {
			if err := m.Notification[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("notification" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("notification" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this v1 get notification v1 response based on the context it is used
func (m *V1GetNotificationV1Response) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateNotification(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V1GetNotificationV1Response) contextValidateNotification(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Notification); i++ {

		if m.Notification[i] != nil {
			if err := m.Notification[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("notification" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("notification" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *V1GetNotificationV1Response) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1GetNotificationV1Response) UnmarshalBinary(b []byte) error {
	var res V1GetNotificationV1Response
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
