// Code generated by go-swagger; DO NOT EDIT.

package act_notification_api_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"gitlab.ozon.dev/qa/classroom-4/act-device-api/test/http_clients/generated_client/models"
)

// ActNotificationAPIServiceGetNotificationReader is a Reader for the ActNotificationAPIServiceGetNotification structure.
type ActNotificationAPIServiceGetNotificationReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ActNotificationAPIServiceGetNotificationReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewActNotificationAPIServiceGetNotificationOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewActNotificationAPIServiceGetNotificationDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewActNotificationAPIServiceGetNotificationOK creates a ActNotificationAPIServiceGetNotificationOK with default headers values
func NewActNotificationAPIServiceGetNotificationOK() *ActNotificationAPIServiceGetNotificationOK {
	return &ActNotificationAPIServiceGetNotificationOK{}
}

/*
ActNotificationAPIServiceGetNotificationOK describes a response with status code 200, with default header values.

A successful response.
*/
type ActNotificationAPIServiceGetNotificationOK struct {
	Payload *models.V1GetNotificationV1Response
}

// IsSuccess returns true when this act notification Api service get notification o k response has a 2xx status code
func (o *ActNotificationAPIServiceGetNotificationOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this act notification Api service get notification o k response has a 3xx status code
func (o *ActNotificationAPIServiceGetNotificationOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this act notification Api service get notification o k response has a 4xx status code
func (o *ActNotificationAPIServiceGetNotificationOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this act notification Api service get notification o k response has a 5xx status code
func (o *ActNotificationAPIServiceGetNotificationOK) IsServerError() bool {
	return false
}

// IsCode returns true when this act notification Api service get notification o k response a status code equal to that given
func (o *ActNotificationAPIServiceGetNotificationOK) IsCode(code int) bool {
	return code == 200
}

func (o *ActNotificationAPIServiceGetNotificationOK) Error() string {
	return fmt.Sprintf("[GET /api/v1/notification][%d] actNotificationApiServiceGetNotificationOK  %+v", 200, o.Payload)
}

func (o *ActNotificationAPIServiceGetNotificationOK) String() string {
	return fmt.Sprintf("[GET /api/v1/notification][%d] actNotificationApiServiceGetNotificationOK  %+v", 200, o.Payload)
}

func (o *ActNotificationAPIServiceGetNotificationOK) GetPayload() *models.V1GetNotificationV1Response {
	return o.Payload
}

func (o *ActNotificationAPIServiceGetNotificationOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V1GetNotificationV1Response)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewActNotificationAPIServiceGetNotificationDefault creates a ActNotificationAPIServiceGetNotificationDefault with default headers values
func NewActNotificationAPIServiceGetNotificationDefault(code int) *ActNotificationAPIServiceGetNotificationDefault {
	return &ActNotificationAPIServiceGetNotificationDefault{
		_statusCode: code,
	}
}

/*
ActNotificationAPIServiceGetNotificationDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type ActNotificationAPIServiceGetNotificationDefault struct {
	_statusCode int

	Payload *models.GooglerpcStatus
}

// Code gets the status code for the act notification Api service get notification default response
func (o *ActNotificationAPIServiceGetNotificationDefault) Code() int {
	return o._statusCode
}

// IsSuccess returns true when this act notification Api service get notification default response has a 2xx status code
func (o *ActNotificationAPIServiceGetNotificationDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this act notification Api service get notification default response has a 3xx status code
func (o *ActNotificationAPIServiceGetNotificationDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this act notification Api service get notification default response has a 4xx status code
func (o *ActNotificationAPIServiceGetNotificationDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this act notification Api service get notification default response has a 5xx status code
func (o *ActNotificationAPIServiceGetNotificationDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this act notification Api service get notification default response a status code equal to that given
func (o *ActNotificationAPIServiceGetNotificationDefault) IsCode(code int) bool {
	return o._statusCode == code
}

func (o *ActNotificationAPIServiceGetNotificationDefault) Error() string {
	return fmt.Sprintf("[GET /api/v1/notification][%d] ActNotificationApiService_GetNotification default  %+v", o._statusCode, o.Payload)
}

func (o *ActNotificationAPIServiceGetNotificationDefault) String() string {
	return fmt.Sprintf("[GET /api/v1/notification][%d] ActNotificationApiService_GetNotification default  %+v", o._statusCode, o.Payload)
}

func (o *ActNotificationAPIServiceGetNotificationDefault) GetPayload() *models.GooglerpcStatus {
	return o.Payload
}

func (o *ActNotificationAPIServiceGetNotificationDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GooglerpcStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
