// Code generated by go-swagger; DO NOT EDIT.

package act_notification_api_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewActNotificationAPIServiceAckNotificationParams creates a new ActNotificationAPIServiceAckNotificationParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewActNotificationAPIServiceAckNotificationParams() *ActNotificationAPIServiceAckNotificationParams {
	return &ActNotificationAPIServiceAckNotificationParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewActNotificationAPIServiceAckNotificationParamsWithTimeout creates a new ActNotificationAPIServiceAckNotificationParams object
// with the ability to set a timeout on a request.
func NewActNotificationAPIServiceAckNotificationParamsWithTimeout(timeout time.Duration) *ActNotificationAPIServiceAckNotificationParams {
	return &ActNotificationAPIServiceAckNotificationParams{
		timeout: timeout,
	}
}

// NewActNotificationAPIServiceAckNotificationParamsWithContext creates a new ActNotificationAPIServiceAckNotificationParams object
// with the ability to set a context for a request.
func NewActNotificationAPIServiceAckNotificationParamsWithContext(ctx context.Context) *ActNotificationAPIServiceAckNotificationParams {
	return &ActNotificationAPIServiceAckNotificationParams{
		Context: ctx,
	}
}

// NewActNotificationAPIServiceAckNotificationParamsWithHTTPClient creates a new ActNotificationAPIServiceAckNotificationParams object
// with the ability to set a custom HTTPClient for a request.
func NewActNotificationAPIServiceAckNotificationParamsWithHTTPClient(client *http.Client) *ActNotificationAPIServiceAckNotificationParams {
	return &ActNotificationAPIServiceAckNotificationParams{
		HTTPClient: client,
	}
}

/*
ActNotificationAPIServiceAckNotificationParams contains all the parameters to send to the API endpoint

	for the act notification Api service ack notification operation.

	Typically these are written to a http.Request.
*/
type ActNotificationAPIServiceAckNotificationParams struct {

	// NotificationID.
	//
	// Format: uint64
	NotificationID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the act notification Api service ack notification params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ActNotificationAPIServiceAckNotificationParams) WithDefaults() *ActNotificationAPIServiceAckNotificationParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the act notification Api service ack notification params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ActNotificationAPIServiceAckNotificationParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the act notification Api service ack notification params
func (o *ActNotificationAPIServiceAckNotificationParams) WithTimeout(timeout time.Duration) *ActNotificationAPIServiceAckNotificationParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the act notification Api service ack notification params
func (o *ActNotificationAPIServiceAckNotificationParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the act notification Api service ack notification params
func (o *ActNotificationAPIServiceAckNotificationParams) WithContext(ctx context.Context) *ActNotificationAPIServiceAckNotificationParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the act notification Api service ack notification params
func (o *ActNotificationAPIServiceAckNotificationParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the act notification Api service ack notification params
func (o *ActNotificationAPIServiceAckNotificationParams) WithHTTPClient(client *http.Client) *ActNotificationAPIServiceAckNotificationParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the act notification Api service ack notification params
func (o *ActNotificationAPIServiceAckNotificationParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithNotificationID adds the notificationID to the act notification Api service ack notification params
func (o *ActNotificationAPIServiceAckNotificationParams) WithNotificationID(notificationID string) *ActNotificationAPIServiceAckNotificationParams {
	o.SetNotificationID(notificationID)
	return o
}

// SetNotificationID adds the notificationId to the act notification Api service ack notification params
func (o *ActNotificationAPIServiceAckNotificationParams) SetNotificationID(notificationID string) {
	o.NotificationID = notificationID
}

// WriteToRequest writes these params to a swagger request
func (o *ActNotificationAPIServiceAckNotificationParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param notificationId
	if err := r.SetPathParam("notificationId", o.NotificationID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
