// Code generated by go-swagger; DO NOT EDIT.

package act_notification_api_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"gitlab.ozon.dev/qa/classroom-4/act-device-api/test/http_clients/generated_client/models"
)

// ActNotificationAPIServiceSendNotificationV1Reader is a Reader for the ActNotificationAPIServiceSendNotificationV1 structure.
type ActNotificationAPIServiceSendNotificationV1Reader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ActNotificationAPIServiceSendNotificationV1Reader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewActNotificationAPIServiceSendNotificationV1OK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewActNotificationAPIServiceSendNotificationV1Default(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewActNotificationAPIServiceSendNotificationV1OK creates a ActNotificationAPIServiceSendNotificationV1OK with default headers values
func NewActNotificationAPIServiceSendNotificationV1OK() *ActNotificationAPIServiceSendNotificationV1OK {
	return &ActNotificationAPIServiceSendNotificationV1OK{}
}

/*
ActNotificationAPIServiceSendNotificationV1OK describes a response with status code 200, with default header values.

A successful response.
*/
type ActNotificationAPIServiceSendNotificationV1OK struct {
	Payload *models.V1SendNotificationV1Response
}

// IsSuccess returns true when this act notification Api service send notification v1 o k response has a 2xx status code
func (o *ActNotificationAPIServiceSendNotificationV1OK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this act notification Api service send notification v1 o k response has a 3xx status code
func (o *ActNotificationAPIServiceSendNotificationV1OK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this act notification Api service send notification v1 o k response has a 4xx status code
func (o *ActNotificationAPIServiceSendNotificationV1OK) IsClientError() bool {
	return false
}

// IsServerError returns true when this act notification Api service send notification v1 o k response has a 5xx status code
func (o *ActNotificationAPIServiceSendNotificationV1OK) IsServerError() bool {
	return false
}

// IsCode returns true when this act notification Api service send notification v1 o k response a status code equal to that given
func (o *ActNotificationAPIServiceSendNotificationV1OK) IsCode(code int) bool {
	return code == 200
}

func (o *ActNotificationAPIServiceSendNotificationV1OK) Error() string {
	return fmt.Sprintf("[POST /api/v1/notification][%d] actNotificationApiServiceSendNotificationV1OK  %+v", 200, o.Payload)
}

func (o *ActNotificationAPIServiceSendNotificationV1OK) String() string {
	return fmt.Sprintf("[POST /api/v1/notification][%d] actNotificationApiServiceSendNotificationV1OK  %+v", 200, o.Payload)
}

func (o *ActNotificationAPIServiceSendNotificationV1OK) GetPayload() *models.V1SendNotificationV1Response {
	return o.Payload
}

func (o *ActNotificationAPIServiceSendNotificationV1OK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V1SendNotificationV1Response)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewActNotificationAPIServiceSendNotificationV1Default creates a ActNotificationAPIServiceSendNotificationV1Default with default headers values
func NewActNotificationAPIServiceSendNotificationV1Default(code int) *ActNotificationAPIServiceSendNotificationV1Default {
	return &ActNotificationAPIServiceSendNotificationV1Default{
		_statusCode: code,
	}
}

/*
ActNotificationAPIServiceSendNotificationV1Default describes a response with status code -1, with default header values.

An unexpected error response.
*/
type ActNotificationAPIServiceSendNotificationV1Default struct {
	_statusCode int

	Payload *models.GooglerpcStatus
}

// Code gets the status code for the act notification Api service send notification v1 default response
func (o *ActNotificationAPIServiceSendNotificationV1Default) Code() int {
	return o._statusCode
}

// IsSuccess returns true when this act notification Api service send notification v1 default response has a 2xx status code
func (o *ActNotificationAPIServiceSendNotificationV1Default) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this act notification Api service send notification v1 default response has a 3xx status code
func (o *ActNotificationAPIServiceSendNotificationV1Default) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this act notification Api service send notification v1 default response has a 4xx status code
func (o *ActNotificationAPIServiceSendNotificationV1Default) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this act notification Api service send notification v1 default response has a 5xx status code
func (o *ActNotificationAPIServiceSendNotificationV1Default) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this act notification Api service send notification v1 default response a status code equal to that given
func (o *ActNotificationAPIServiceSendNotificationV1Default) IsCode(code int) bool {
	return o._statusCode == code
}

func (o *ActNotificationAPIServiceSendNotificationV1Default) Error() string {
	return fmt.Sprintf("[POST /api/v1/notification][%d] ActNotificationApiService_SendNotificationV1 default  %+v", o._statusCode, o.Payload)
}

func (o *ActNotificationAPIServiceSendNotificationV1Default) String() string {
	return fmt.Sprintf("[POST /api/v1/notification][%d] ActNotificationApiService_SendNotificationV1 default  %+v", o._statusCode, o.Payload)
}

func (o *ActNotificationAPIServiceSendNotificationV1Default) GetPayload() *models.GooglerpcStatus {
	return o.Payload
}

func (o *ActNotificationAPIServiceSendNotificationV1Default) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GooglerpcStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
