// Code generated by go-swagger; DO NOT EDIT.

package act_notification_api_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewActNotificationAPIServiceGetNotificationParams creates a new ActNotificationAPIServiceGetNotificationParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewActNotificationAPIServiceGetNotificationParams() *ActNotificationAPIServiceGetNotificationParams {
	return &ActNotificationAPIServiceGetNotificationParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewActNotificationAPIServiceGetNotificationParamsWithTimeout creates a new ActNotificationAPIServiceGetNotificationParams object
// with the ability to set a timeout on a request.
func NewActNotificationAPIServiceGetNotificationParamsWithTimeout(timeout time.Duration) *ActNotificationAPIServiceGetNotificationParams {
	return &ActNotificationAPIServiceGetNotificationParams{
		timeout: timeout,
	}
}

// NewActNotificationAPIServiceGetNotificationParamsWithContext creates a new ActNotificationAPIServiceGetNotificationParams object
// with the ability to set a context for a request.
func NewActNotificationAPIServiceGetNotificationParamsWithContext(ctx context.Context) *ActNotificationAPIServiceGetNotificationParams {
	return &ActNotificationAPIServiceGetNotificationParams{
		Context: ctx,
	}
}

// NewActNotificationAPIServiceGetNotificationParamsWithHTTPClient creates a new ActNotificationAPIServiceGetNotificationParams object
// with the ability to set a custom HTTPClient for a request.
func NewActNotificationAPIServiceGetNotificationParamsWithHTTPClient(client *http.Client) *ActNotificationAPIServiceGetNotificationParams {
	return &ActNotificationAPIServiceGetNotificationParams{
		HTTPClient: client,
	}
}

/*
ActNotificationAPIServiceGetNotificationParams contains all the parameters to send to the API endpoint

	for the act notification Api service get notification operation.

	Typically these are written to a http.Request.
*/
type ActNotificationAPIServiceGetNotificationParams struct {

	// DeviceID.
	//
	// Format: uint64
	DeviceID *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the act notification Api service get notification params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ActNotificationAPIServiceGetNotificationParams) WithDefaults() *ActNotificationAPIServiceGetNotificationParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the act notification Api service get notification params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ActNotificationAPIServiceGetNotificationParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the act notification Api service get notification params
func (o *ActNotificationAPIServiceGetNotificationParams) WithTimeout(timeout time.Duration) *ActNotificationAPIServiceGetNotificationParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the act notification Api service get notification params
func (o *ActNotificationAPIServiceGetNotificationParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the act notification Api service get notification params
func (o *ActNotificationAPIServiceGetNotificationParams) WithContext(ctx context.Context) *ActNotificationAPIServiceGetNotificationParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the act notification Api service get notification params
func (o *ActNotificationAPIServiceGetNotificationParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the act notification Api service get notification params
func (o *ActNotificationAPIServiceGetNotificationParams) WithHTTPClient(client *http.Client) *ActNotificationAPIServiceGetNotificationParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the act notification Api service get notification params
func (o *ActNotificationAPIServiceGetNotificationParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDeviceID adds the deviceID to the act notification Api service get notification params
func (o *ActNotificationAPIServiceGetNotificationParams) WithDeviceID(deviceID *string) *ActNotificationAPIServiceGetNotificationParams {
	o.SetDeviceID(deviceID)
	return o
}

// SetDeviceID adds the deviceId to the act notification Api service get notification params
func (o *ActNotificationAPIServiceGetNotificationParams) SetDeviceID(deviceID *string) {
	o.DeviceID = deviceID
}

// WriteToRequest writes these params to a swagger request
func (o *ActNotificationAPIServiceGetNotificationParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.DeviceID != nil {

		// query param deviceId
		var qrDeviceID string

		if o.DeviceID != nil {
			qrDeviceID = *o.DeviceID
		}
		qDeviceID := qrDeviceID
		if qDeviceID != "" {

			if err := r.SetQueryParam("deviceId", qDeviceID); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
